### ISSUE TITLE
Domain lock not working

### ISSUE THREAD

**Issue by andrea78** [MichaelXF/js-confuser#122] opened 2024-01-05 00:54 UTC
Hi @MichaelXF 
Great tool, Congratulations!
Thanks for releasing it!
I'd like to use the domain-locking feature, but can't get it to work.
Am I missing something? Do I need to enable cli-option to make domain locking work?
I'm running on node v16.20.2.

**Comment by Mrgaton** [comment] 2024-03-02 22:09
I thing that the problem is the lock:integrity

**Comment by MichaelXF** [comment] 2024-11-12 03:45
I believe this issue is solved. Moving to #144 

The website had UI problems saving the domainLock properly, but NPM version was unaffected.

**Closed by MichaelXF** 2024-11-12 03:45 UTC
Labels: bug
