### ISSUE TITLE
Exception with important variables

### ISSUE THREAD

**Issue by EndryosOficialOne** [MichaelXF/js-confuser#111] opened 2023-10-27 04:14 UTC
**Is your feature request related to a problem? Please describe.**
I always feel sad when I see that my code throws an error simply because the obfuscator renames an important variable in my code.

**Describe the solution you'd like**
It would be perfect if there was an additional option, like JSON, in the advanced options section to add important variables that should not be renamed.

**Additional context**
On the website https://obfuscator.io/, the Reserved Strings option works perfectly.

**Comment by Le0Developer** [comment] 2023-11-28 13:14
Duplicate of #54, pass a custom `renameVariables` function.
<img width="451" alt="image" src="https://github.com/MichaelXF/js-confuser/assets/40232557/3ce7a8e4-ae51-4921-a7db-ff103a5f42be">

**Closed** 2023-11-30 23:25 UTC
Labels: enhancement
