### ISSUE TITLE
Domain lock leaves the domain string unprotected

### ISSUE THREAD

**Issue by Mrgaton** [MichaelXF/js-confuser#124] opened 2024-03-02 22:11 UTC
In the output code you can repeatedly see the regex of the domain  that has been locked and easily be changed with a simple notepad replace

**Comment by Le0Developer** [comment] 2024-03-18 13:18
basically duplicate of #115

**Comment by MichaelXF** [comment] 2024-09-30 15:54
Fixed in 2.0 (Currently [2.0.0-alpha.2](https://www.npmjs.com/package/js-confuser/v/2.0.0-alpha.2)). Now uses the RegExp constructor and is further protected by String Concealing / other obfuscations.

**Closed by MichaelXF** 2024-09-30 15:54 UTC
Labels: enhancement
